version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Installing Maven..."
      - curl -sL https://archive.apache.org/dist/maven/maven-3/3.9.4/binaries/apache-maven-3.9.4-bin.tar.gz -o /tmp/maven.tar.gz
      - tar -xzf /tmp/maven.tar.gz -C /tmp
      - export M2_HOME=/tmp/apache-maven-3.9.4
      - export PATH=$M2_HOME/bin:$PATH
      - mvn --version
      - aws --version

  pre_build:
    commands:
      - echo "Setting up ECR variables..."
      - REPOSITORY_URI=354612239460.dkr.ecr.ap-south-1.amazonaws.com/inventrade
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=BUILD-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $REPOSITORY_URI

  build:
    commands:
      - echo "Build started on `date`"
      - echo "Running Maven build..."
      - cd inventrade   # if your pom.xml is inside inventrade folder
      - mvn clean package -DskipTests
      - echo "Building Docker image..."
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Pushing Docker images..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Writing imagedefinitions.json..."
      - DOCKER_CONTAINER_NAME=inventrade
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - inventrade/target/inventrade-0.0.1-SNAPSHOT.jar
